---
- name: Setup froggy
  hosts: default

  tasks:
    - name: Install required packages
      become: true
      community.general.apk:
        name:
          - nginx
        state: latest
        update_cache: true

    - name: Secrets directory present
      ansible.builtin.file:
        path: ~/secrets
        state: directory
        mode: '700'

    - name: Variables file present
      ansible.builtin.file:
        path: ~/secrets/variables
        state: touch
        mode: '600'

    - name: Github key in secrets
      ansible.builtin.lineinfile:
        path: ~/secrets/variables
        line: 'export GITHUB_TOKEN={{ GITHUB_TOKEN }}'
        state: present

    - name: Copy nginx config
      become: true
      ansible.builtin.copy:
        src: ../../scripts/bercik.conf
        dest: /etc/nginx/nginx.conf
        mode: '0644'

    - name: Make sure cert directories are present
      become: true
      ansible.builtin.file:
        path: /etc/certs/bercik.xyz/
        state: directory
        owner: 1000
        mode: '0700'

    - name: Keep d-h parameters file in certs
      become: true
      ansible.builtin.get_url:
        url: https://ssl-config.mozilla.org/ffdhe2048.txt
        dest: /etc/certs/dhparam
        mode: '0644'

    - name: Nginx is running
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
